#
# Create sources list
#
set(${SrcSubDir}_${SrcSubSubDir}_Srcs
      ASCIIEWriter.cpp
      ASCIIFile.cpp
      ASCIINWriter.cpp
      ASCIIReader.cpp
      ASCIIRWriter.cpp 
      ASCIIWriter.cpp
      CFLTimestepFileDefs.cpp
      CFLTimestepFile.cpp
      ControlInterface.cpp
      ControlInterfaceDefs.cpp
      EnergyFileDefs.cpp
      FDSHSplittingFile.cpp
      ParametersFileDefs.cpp
      ParametersFile.cpp
      PhysicalSplittingFile.cpp
      SpectrumFileDefs.cpp
      SpectralSplittingFile.cpp
      SplittingFile.cpp
      SplittingFileDefs.cpp
      StdMessageDefs.cpp
      StdMessage.cpp 
      TimeFile.cpp
      TimeFileDefs.cpp
      XMLReaderDefs.cpp
      XMLReader.cpp
      )
