#
# Add the unit tests directory
#
add_subdirectory("UnitTests")

#
# Add the precision tests directory
#
add_subdirectory("PrecisionTests")

#
# Add the speed tests directory
#
add_subdirectory("SpeedTests")

#
# Add the parallelisation tests directory
#
add_subdirectory("ParallelisationTests")

#
# Add the physical tests directory
#
add_subdirectory("PhysicalTests")

#
# Add the experimental tests directory
#
add_subdirectory("ExperimentalTests")
